###########################################################
# Dockercompose pour gerer l'ensemble des conteneurs
# Basé sur Debian
###########################################################

# Version:
version: '3'

# Represente les images que nous utilisons:
services:

  ########################################
  mariadb:
    container_name: mariadb
    networks:
      - inception
    build:
      context: requirements/mariadb
      dockerfile: Dockerfile
    env_file: .env
    # volumes:
      # - mariadb:/var/lib/mysql
    expose:
      - "3306"
    restart: unless-stopped

  ########################################
  nginx:
    container_name: nginx
    networks:
      - inception
    depends_on:
      - wordpress
    build: 
      context: requirements/nginx
      dockerfile: Dockerfile
    env_file: .env
    ports:
      - "443:443"
    # volumes:
	  # - wordpress:/var/www/wordpress
    restart: on-failure

  ########################################
  wordpress:
    container_name: wordpress
    networks:
      - inception
    depends_on:
      - mariadb
    build: 
      context: requirements/wordpress
      dockerfile: Dockerfile
    env_file: .env
    # volumes:
      # - wordpress:/var/www/wordpress
    expose:
      - "9000"
    restart: on-failure


networks:
  inception:
    driver: bridge

